runtime: python310  # or python311 if you prefer
instance_class: F1  # optional

handlers:
  - url: /.*
    script: auto

entrypoint: gunicorn -b :$PORT main:application

# Optional scaling (avoids the max_instances warning)
automatic_scaling:
  max_instances: 5
